server:
  port: 9884
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9881/eureka/
  instance:
    lease-expiration-duration-in-seconds: 90 #服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-renewal-interval-in-seconds: 30 #定义服务续约任务（心跳）的调用间隔，单位：秒

spring:
  application:
    name: PROJECT-OPEN-BIRTHDATE-ITEM
  redis:
    host: localhost
    port: 6379
    timeout: 5000
    #password: 123456
    lettuce:
      pool:
        max-active: 8
        max-idle: 100
        min-idle: 20
        max-wait: 100

  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maximum-pool-size: 10
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.200:3306/project-birthdate-item?useUnicode=true&amp&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  #配置文件传输
  servlet:
    multipart:
      max-file-size: 20MB

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/com.business.mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/com.business.mapper/*Mapper.xml
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: default
      db-type: mysql

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: countSql

logging:
  level:
    com: info
  file: log/catalina.out

#系统我的公共配置
my-configuration:
      #图片上传路径
      uploadPath: /home/project/file/
      #图片访问路径
      imagePath: /file/
      #项目缓存存储时间
      sessionTimeout: 7200
      #阿里信息
      accessKeyId: LTAImOWJOk8m1LO7
      accessKeySecret: hUd5EmRbjp8HX6czYSSwkebyDsvs1z
      aliOssEndpoint: http://oss-cn-hongkong.aliyuncs.com
      aliOssBucketNameUser: sudakeji
      #验证码长度
      codeLength: 6
      #eth 节点地址
      ethNodesReqAddr: http://127.0.0.1:8545
      #ethNodesReqAddr: https://mainnet.infura.io/3f727c7ce8434106809d5cc2463ff779
      #ethNodesReqAddr: https://ropsten.infura.io/3f727c7ce8434106809d5cc2463ff779
      ethQueryOrderRecordReqAddr: http://api.etherscan.io/api?module=account&action=txlist&page=&offset=&sort=desc&apikey=7X8Y5FA3K5FSG1D3S57B6F5EBPT9QC1AYR
      #用户推广注册页
      popularizePageUrl: http://192.168.1.6:9999/page/register/mobile_reg.html?invitationCode=
      # 用户推广二维码
      popularizeQrCode: http://192.168.1.6:9999/platform/app/myTeam/getQrcode?invitationCode=






