server:
  port: 9881
eureka:
  instance:
    hostname: 127.0.0.1 #设置当前实例的主机名称

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  server:
    enable-self-preservation: false  #关闭保护机制 有服务宕机就剔除 不给重新恢复时间
    eviction-interval-timer-in-ms: 2000  #剔除间隔时间

spring:
  application:
    name: COMMON-EUREKA-SERVER
logging:
  level:
    com: debug
  file: log/eureka.log
