server:
  port: 10007
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.6:10001/eureka/
  instance:
    lease-expiration-duration-in-seconds: 90 #服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-renewal-interval-in-seconds: 30 #定义服务续约任务（心跳）的调用间隔，单位：秒

spring:
  application:
    name: PROJECT-PLATFORM-ITEM
  redis:
    host: 192.168.1.6
    port: 6379
    timeout: 5000
    #password: 123456
    lettuce:
      pool:
        max-active: 8
        max-idle: 100
        min-idle: 20
        max-wait: 100

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.6:3307/suda_platform?useUnicode=true&amp&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
        maximum-pool-size: 100
        idle-timeout: 300000

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  #配置文件传输
  servlet:
    multipart:
      max-file-size: 20MB
  zipkin:
    base-url: http://localhost:9411/

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: default
      db-type: mysql

  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
  type-aliases-package: com.shop.entity

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: countSql

logging:
  level:
    com: info
  file: log/catalina.out

#系统我的公共配置
my-configuration:
      #图片上传路径
      uploadPath: /home/project/file/
      #图片访问路径
      imagePath: /file/
      #项目缓存存储时间
      sessionTimeout: 7200
      #阿里信息
      accessKeyId: LTAImOWJOk8m1LO7
      accessKeySecret: hUd5EmRbjp8HX6czYSSwkebyDsvs1z
      aliOssEndpoint: http://oss-cn-hongkong.aliyuncs.com
      aliOssBucketNameUser: sudakeji
      #验证码长度
      codeLength: 6
      #eth 节点地址
      ethNodesReqAddr: http://127.0.0.1:8545
      #ethNodesReqAddr: https://mainnet.infura.io/3f727c7ce8434106809d5cc2463ff779
      #ethNodesReqAddr: https://ropsten.infura.io/3f727c7ce8434106809d5cc2463ff779
      ethQueryOrderRecordReqAddr: http://api.etherscan.io/api?module=account&action=txlist&page=&offset=&sort=desc&apikey=7X8Y5FA3K5FSG1D3S57B6F5EBPT9QC1AYR
      #用户推广注册页
      popularizePageUrl: http://175w302m69.51mypc.cn:35291/page/register/mobile_reg.html?invitationCode=
      # 用户推广二维码
      popularizeQrCode: http://175w302m69.51mypc.cn:35291/platform/app/myTeam/getQrcode?invitationCode=




tx-lcn:
  client:
    manager-address: 127.0.0.1:10003
