server:
  port: 9885
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9881/eureka/
  instance:
    lease-expiration-duration-in-seconds: 90 #服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-renewal-interval-in-seconds: 30 #定义服务续约任务（心跳）的调用间隔，单位：秒

spring:
  application:
    name: COMMON-TXLCN-MANAGER-SERVER
  redis:
    host: localhost
    port: 6379
    timeout: 5000
    #password: 123456

  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maximum-pool-size: 10
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.200:3306/project-birthdate-item?useUnicode=true&amp&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  #配置文件传输
  servlet:
    multipart:
      max-file-size: 20MB

  zipkin:
    base-url: http://localhost:9411
#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: countSql

logging:
  level:
    com: info
  file: log/txlcn-manager.log

tx-lcn:
  manager:
    port: 9886
    host: 127.0.0.1
    admin-key: 123456
  logger:
    enabled: true
    jdbc-url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}